framework:
    secret: '%env(APP_SECRET)%'
    default_locale: pt_BR
    csrf_protection: ~
    http_method_override: true

    # uncomment this entire section to enable sessions
    session:
        handler_id: ~

    php_errors:
        log: true
